kits:
  pvp:
    price: 0
    name: "PvP"
    material: WOOD_SWORD
    lore: []
  athlete:
    price: 1500
    name: "Athlete"
    material: SUGAR
    lore: []
  frog:
    price: 1500
    name: "Frog"
    material: SUGAR
    lore: []
spawnTeleportDelayInSeconds: 5
repair:
  cost: 35
spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
book:
  material: "BOOK"
  displayName: "&eKits"